// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/TargetLib/v1/manager.proto

package targetlibv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TargetLibManager_GetVersion_FullMethodName      = "/targetlib.v1.TargetLibManager/GetVersion"
	TargetLibManager_GetCapabilities_FullMethodName = "/targetlib.v1.TargetLibManager/GetCapabilities"
	TargetLibManager_CheckConfig_FullMethodName     = "/targetlib.v1.TargetLibManager/CheckConfig"
	TargetLibManager_Start_FullMethodName           = "/targetlib.v1.TargetLibManager/Start"
	TargetLibManager_Reload_FullMethodName          = "/targetlib.v1.TargetLibManager/Reload"
	TargetLibManager_Restart_FullMethodName         = "/targetlib.v1.TargetLibManager/Restart"
	TargetLibManager_Stop_FullMethodName            = "/targetlib.v1.TargetLibManager/Stop"
	TargetLibManager_GetState_FullMethodName        = "/targetlib.v1.TargetLibManager/GetState"
	TargetLibManager_SubscribeState_FullMethodName  = "/targetlib.v1.TargetLibManager/SubscribeState"
)

// TargetLibManagerClient is the client API for TargetLibManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TargetLibManagerClient interface {
	GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
	GetCapabilities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
	CheckConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*CheckConfigResponse, error)
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	Stop(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OperationResponse, error)
	GetState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServiceState, error)
	SubscribeState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceState], error)
}

type targetLibManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewTargetLibManagerClient(cc grpc.ClientConnInterface) TargetLibManagerClient {
	return &targetLibManagerClient{cc}
}

func (c *targetLibManagerClient) GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, TargetLibManager_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibManagerClient) GetCapabilities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, TargetLibManager_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibManagerClient) CheckConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*CheckConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckConfigResponse)
	err := c.cc.Invoke(ctx, TargetLibManager_CheckConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibManagerClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, TargetLibManager_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibManagerClient) Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, TargetLibManager_Reload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibManagerClient) Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, TargetLibManager_Restart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibManagerClient) Stop(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, TargetLibManager_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibManagerClient) GetState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServiceState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceState)
	err := c.cc.Invoke(ctx, TargetLibManager_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibManagerClient) SubscribeState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TargetLibManager_ServiceDesc.Streams[0], TargetLibManager_SubscribeState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, ServiceState]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TargetLibManager_SubscribeStateClient = grpc.ServerStreamingClient[ServiceState]

// TargetLibManagerServer is the server API for TargetLibManager service.
// All implementations must embed UnimplementedTargetLibManagerServer
// for forward compatibility.
type TargetLibManagerServer interface {
	GetVersion(context.Context, *emptypb.Empty) (*VersionResponse, error)
	GetCapabilities(context.Context, *emptypb.Empty) (*CapabilitiesResponse, error)
	CheckConfig(context.Context, *ConfigRequest) (*CheckConfigResponse, error)
	Start(context.Context, *StartRequest) (*OperationResponse, error)
	Reload(context.Context, *ReloadRequest) (*OperationResponse, error)
	Restart(context.Context, *RestartRequest) (*OperationResponse, error)
	Stop(context.Context, *emptypb.Empty) (*OperationResponse, error)
	GetState(context.Context, *emptypb.Empty) (*ServiceState, error)
	SubscribeState(*emptypb.Empty, grpc.ServerStreamingServer[ServiceState]) error
	mustEmbedUnimplementedTargetLibManagerServer()
}

// UnimplementedTargetLibManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTargetLibManagerServer struct{}

func (UnimplementedTargetLibManagerServer) GetVersion(context.Context, *emptypb.Empty) (*VersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedTargetLibManagerServer) GetCapabilities(context.Context, *emptypb.Empty) (*CapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedTargetLibManagerServer) CheckConfig(context.Context, *ConfigRequest) (*CheckConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckConfig not implemented")
}
func (UnimplementedTargetLibManagerServer) Start(context.Context, *StartRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedTargetLibManagerServer) Reload(context.Context, *ReloadRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reload not implemented")
}
func (UnimplementedTargetLibManagerServer) Restart(context.Context, *RestartRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Restart not implemented")
}
func (UnimplementedTargetLibManagerServer) Stop(context.Context, *emptypb.Empty) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedTargetLibManagerServer) GetState(context.Context, *emptypb.Empty) (*ServiceState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedTargetLibManagerServer) SubscribeState(*emptypb.Empty, grpc.ServerStreamingServer[ServiceState]) error {
	return status.Error(codes.Unimplemented, "method SubscribeState not implemented")
}
func (UnimplementedTargetLibManagerServer) mustEmbedUnimplementedTargetLibManagerServer() {}
func (UnimplementedTargetLibManagerServer) testEmbeddedByValue()                          {}

// UnsafeTargetLibManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TargetLibManagerServer will
// result in compilation errors.
type UnsafeTargetLibManagerServer interface {
	mustEmbedUnimplementedTargetLibManagerServer()
}

func RegisterTargetLibManagerServer(s grpc.ServiceRegistrar, srv TargetLibManagerServer) {
	// If the following call panics, it indicates UnimplementedTargetLibManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TargetLibManager_ServiceDesc, srv)
}

func _TargetLibManager_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibManagerServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLibManager_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibManagerServer).GetVersion(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLibManager_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibManagerServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLibManager_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibManagerServer).GetCapabilities(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLibManager_CheckConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibManagerServer).CheckConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLibManager_CheckConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibManagerServer).CheckConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLibManager_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibManagerServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLibManager_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibManagerServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLibManager_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibManagerServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLibManager_Reload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibManagerServer).Reload(ctx, req.(*ReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLibManager_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibManagerServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLibManager_Restart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibManagerServer).Restart(ctx, req.(*RestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLibManager_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibManagerServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLibManager_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibManagerServer).Stop(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLibManager_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibManagerServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLibManager_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibManagerServer).GetState(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLibManager_SubscribeState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TargetLibManagerServer).SubscribeState(m, &grpc.GenericServerStream[emptypb.Empty, ServiceState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TargetLibManager_SubscribeStateServer = grpc.ServerStreamingServer[ServiceState]

// TargetLibManager_ServiceDesc is the grpc.ServiceDesc for TargetLibManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TargetLibManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "targetlib.v1.TargetLibManager",
	HandlerType: (*TargetLibManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _TargetLibManager_GetVersion_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _TargetLibManager_GetCapabilities_Handler,
		},
		{
			MethodName: "CheckConfig",
			Handler:    _TargetLibManager_CheckConfig_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _TargetLibManager_Start_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _TargetLibManager_Reload_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _TargetLibManager_Restart_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _TargetLibManager_Stop_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _TargetLibManager_GetState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeState",
			Handler:       _TargetLibManager_SubscribeState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/TargetLib/v1/manager.proto",
}
