// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/TargetLib/targetlib.proto

package targetlib

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TargetLib_Start_FullMethodName                        = "/targetlib.TargetLib/Start"
	TargetLib_Restart_FullMethodName                      = "/targetlib.TargetLib/Restart"
	TargetLib_Stop_FullMethodName                         = "/targetlib.TargetLib/Stop"
	TargetLib_GetState_FullMethodName                     = "/targetlib.TargetLib/GetState"
	TargetLib_SubscribeState_FullMethodName               = "/targetlib.TargetLib/SubscribeState"
	TargetLib_SubscribeLogs_FullMethodName                = "/targetlib.TargetLib/SubscribeLogs"
	TargetLib_SubscribeTraffic_FullMethodName             = "/targetlib.TargetLib/SubscribeTraffic"
	TargetLib_CloseConnection_FullMethodName              = "/targetlib.TargetLib/CloseConnection"
	TargetLib_CloseAllConnections_FullMethodName          = "/targetlib.TargetLib/CloseAllConnections"
	TargetLib_ListSubscriptions_FullMethodName            = "/targetlib.TargetLib/ListSubscriptions"
	TargetLib_GetSubscription_FullMethodName              = "/targetlib.TargetLib/GetSubscription"
	TargetLib_AddSubscription_FullMethodName              = "/targetlib.TargetLib/AddSubscription"
	TargetLib_RemoveSubscription_FullMethodName           = "/targetlib.TargetLib/RemoveSubscription"
	TargetLib_RenameSubscription_FullMethodName           = "/targetlib.TargetLib/RenameSubscription"
	TargetLib_SetSubscriptionEnabled_FullMethodName       = "/targetlib.TargetLib/SetSubscriptionEnabled"
	TargetLib_ConfigureSubscriptionUpdates_FullMethodName = "/targetlib.TargetLib/ConfigureSubscriptionUpdates"
	TargetLib_UpdateSubscription_FullMethodName           = "/targetlib.TargetLib/UpdateSubscription"
	TargetLib_GetResolvedEndpoints_FullMethodName         = "/targetlib.TargetLib/GetResolvedEndpoints"
	TargetLib_SubscribeSubscriptionEvents_FullMethodName  = "/targetlib.TargetLib/SubscribeSubscriptionEvents"
	TargetLib_GetNodePool_FullMethodName                  = "/targetlib.TargetLib/GetNodePool"
	TargetLib_SelectNode_FullMethodName                   = "/targetlib.TargetLib/SelectNode"
	TargetLib_GetProxyStatus_FullMethodName               = "/targetlib.TargetLib/GetProxyStatus"
	TargetLib_GetRuntimeConfig_FullMethodName             = "/targetlib.TargetLib/GetRuntimeConfig"
	TargetLib_UpdateRuntimeConfig_FullMethodName          = "/targetlib.TargetLib/UpdateRuntimeConfig"
	TargetLib_GetIpInfo_FullMethodName                    = "/targetlib.TargetLib/GetIpInfo"
	TargetLib_UpsertRoute_FullMethodName                  = "/targetlib.TargetLib/UpsertRoute"
	TargetLib_DeleteRoute_FullMethodName                  = "/targetlib.TargetLib/DeleteRoute"
	TargetLib_ListRoutes_FullMethodName                   = "/targetlib.TargetLib/ListRoutes"
	TargetLib_SelectRouteNode_FullMethodName              = "/targetlib.TargetLib/SelectRouteNode"
)

// TargetLibClient is the client API for TargetLib service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TargetLibClient interface {
	// Layer 1: Basic Proxy Control
	Start(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OperationResponse, error)
	Restart(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OperationResponse, error)
	Stop(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OperationResponse, error)
	GetState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServiceState, error)
	SubscribeState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceState], error)
	SubscribeLogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogBatch], error)
	SubscribeTraffic(ctx context.Context, in *TrafficRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrafficStatus], error)
	CloseConnection(ctx context.Context, in *CloseConnectionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CloseAllConnections(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListSubscriptions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SubscriptionList, error)
	GetSubscription(ctx context.Context, in *SubscriptionId, opts ...grpc.CallOption) (*SubscriptionView, error)
	AddSubscription(ctx context.Context, in *AddSubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionView, error)
	RemoveSubscription(ctx context.Context, in *SubscriptionId, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RenameSubscription(ctx context.Context, in *RenameSubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionView, error)
	SetSubscriptionEnabled(ctx context.Context, in *SetSubscriptionEnabledRequest, opts ...grpc.CallOption) (*SubscriptionView, error)
	ConfigureSubscriptionUpdates(ctx context.Context, in *ConfigureSubscriptionUpdatesRequest, opts ...grpc.CallOption) (*SubscriptionView, error)
	UpdateSubscription(ctx context.Context, in *SubscriptionId, opts ...grpc.CallOption) (*SubscriptionUpdateResult, error)
	GetResolvedEndpoints(ctx context.Context, in *ResolvedEndpointsRequest, opts ...grpc.CallOption) (*ResolvedEndpoints, error)
	SubscribeSubscriptionEvents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscriptionEvent], error)
	GetNodePool(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NodePool, error)
	SelectNode(ctx context.Context, in *SelectNodeRequest, opts ...grpc.CallOption) (*SelectNodeResponse, error)
	GetProxyStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ProxyStatus, error)
	GetRuntimeConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RuntimeConfig, error)
	UpdateRuntimeConfig(ctx context.Context, in *UpdateRuntimeConfigRequest, opts ...grpc.CallOption) (*RuntimeConfig, error)
	GetIpInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*IpInfoResponse, error)
	// Layer 2: Rule-based Routing
	UpsertRoute(ctx context.Context, in *UpsertRouteRequest, opts ...grpc.CallOption) (*RouteInfo, error)
	DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListRoutes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RouteList, error)
	SelectRouteNode(ctx context.Context, in *SelectRouteNodeRequest, opts ...grpc.CallOption) (*SelectNodeResponse, error)
}

type targetLibClient struct {
	cc grpc.ClientConnInterface
}

func NewTargetLibClient(cc grpc.ClientConnInterface) TargetLibClient {
	return &targetLibClient{cc}
}

func (c *targetLibClient) Start(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, TargetLib_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) Restart(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, TargetLib_Restart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) Stop(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, TargetLib_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) GetState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServiceState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceState)
	err := c.cc.Invoke(ctx, TargetLib_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) SubscribeState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TargetLib_ServiceDesc.Streams[0], TargetLib_SubscribeState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, ServiceState]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TargetLib_SubscribeStateClient = grpc.ServerStreamingClient[ServiceState]

func (c *targetLibClient) SubscribeLogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TargetLib_ServiceDesc.Streams[1], TargetLib_SubscribeLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, LogBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TargetLib_SubscribeLogsClient = grpc.ServerStreamingClient[LogBatch]

func (c *targetLibClient) SubscribeTraffic(ctx context.Context, in *TrafficRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrafficStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TargetLib_ServiceDesc.Streams[2], TargetLib_SubscribeTraffic_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TrafficRequest, TrafficStatus]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TargetLib_SubscribeTrafficClient = grpc.ServerStreamingClient[TrafficStatus]

func (c *targetLibClient) CloseConnection(ctx context.Context, in *CloseConnectionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TargetLib_CloseConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) CloseAllConnections(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TargetLib_CloseAllConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) ListSubscriptions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SubscriptionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionList)
	err := c.cc.Invoke(ctx, TargetLib_ListSubscriptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) GetSubscription(ctx context.Context, in *SubscriptionId, opts ...grpc.CallOption) (*SubscriptionView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionView)
	err := c.cc.Invoke(ctx, TargetLib_GetSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) AddSubscription(ctx context.Context, in *AddSubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionView)
	err := c.cc.Invoke(ctx, TargetLib_AddSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) RemoveSubscription(ctx context.Context, in *SubscriptionId, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TargetLib_RemoveSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) RenameSubscription(ctx context.Context, in *RenameSubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionView)
	err := c.cc.Invoke(ctx, TargetLib_RenameSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) SetSubscriptionEnabled(ctx context.Context, in *SetSubscriptionEnabledRequest, opts ...grpc.CallOption) (*SubscriptionView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionView)
	err := c.cc.Invoke(ctx, TargetLib_SetSubscriptionEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) ConfigureSubscriptionUpdates(ctx context.Context, in *ConfigureSubscriptionUpdatesRequest, opts ...grpc.CallOption) (*SubscriptionView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionView)
	err := c.cc.Invoke(ctx, TargetLib_ConfigureSubscriptionUpdates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) UpdateSubscription(ctx context.Context, in *SubscriptionId, opts ...grpc.CallOption) (*SubscriptionUpdateResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionUpdateResult)
	err := c.cc.Invoke(ctx, TargetLib_UpdateSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) GetResolvedEndpoints(ctx context.Context, in *ResolvedEndpointsRequest, opts ...grpc.CallOption) (*ResolvedEndpoints, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolvedEndpoints)
	err := c.cc.Invoke(ctx, TargetLib_GetResolvedEndpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) SubscribeSubscriptionEvents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscriptionEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TargetLib_ServiceDesc.Streams[3], TargetLib_SubscribeSubscriptionEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, SubscriptionEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TargetLib_SubscribeSubscriptionEventsClient = grpc.ServerStreamingClient[SubscriptionEvent]

func (c *targetLibClient) GetNodePool(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NodePool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodePool)
	err := c.cc.Invoke(ctx, TargetLib_GetNodePool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) SelectNode(ctx context.Context, in *SelectNodeRequest, opts ...grpc.CallOption) (*SelectNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectNodeResponse)
	err := c.cc.Invoke(ctx, TargetLib_SelectNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) GetProxyStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ProxyStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProxyStatus)
	err := c.cc.Invoke(ctx, TargetLib_GetProxyStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) GetRuntimeConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RuntimeConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeConfig)
	err := c.cc.Invoke(ctx, TargetLib_GetRuntimeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) UpdateRuntimeConfig(ctx context.Context, in *UpdateRuntimeConfigRequest, opts ...grpc.CallOption) (*RuntimeConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeConfig)
	err := c.cc.Invoke(ctx, TargetLib_UpdateRuntimeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) GetIpInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*IpInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IpInfoResponse)
	err := c.cc.Invoke(ctx, TargetLib_GetIpInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) UpsertRoute(ctx context.Context, in *UpsertRouteRequest, opts ...grpc.CallOption) (*RouteInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteInfo)
	err := c.cc.Invoke(ctx, TargetLib_UpsertRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TargetLib_DeleteRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) ListRoutes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RouteList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteList)
	err := c.cc.Invoke(ctx, TargetLib_ListRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) SelectRouteNode(ctx context.Context, in *SelectRouteNodeRequest, opts ...grpc.CallOption) (*SelectNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectNodeResponse)
	err := c.cc.Invoke(ctx, TargetLib_SelectRouteNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TargetLibServer is the server API for TargetLib service.
// All implementations must embed UnimplementedTargetLibServer
// for forward compatibility.
type TargetLibServer interface {
	// Layer 1: Basic Proxy Control
	Start(context.Context, *emptypb.Empty) (*OperationResponse, error)
	Restart(context.Context, *emptypb.Empty) (*OperationResponse, error)
	Stop(context.Context, *emptypb.Empty) (*OperationResponse, error)
	GetState(context.Context, *emptypb.Empty) (*ServiceState, error)
	SubscribeState(*emptypb.Empty, grpc.ServerStreamingServer[ServiceState]) error
	SubscribeLogs(*emptypb.Empty, grpc.ServerStreamingServer[LogBatch]) error
	SubscribeTraffic(*TrafficRequest, grpc.ServerStreamingServer[TrafficStatus]) error
	CloseConnection(context.Context, *CloseConnectionRequest) (*emptypb.Empty, error)
	CloseAllConnections(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	ListSubscriptions(context.Context, *emptypb.Empty) (*SubscriptionList, error)
	GetSubscription(context.Context, *SubscriptionId) (*SubscriptionView, error)
	AddSubscription(context.Context, *AddSubscriptionRequest) (*SubscriptionView, error)
	RemoveSubscription(context.Context, *SubscriptionId) (*emptypb.Empty, error)
	RenameSubscription(context.Context, *RenameSubscriptionRequest) (*SubscriptionView, error)
	SetSubscriptionEnabled(context.Context, *SetSubscriptionEnabledRequest) (*SubscriptionView, error)
	ConfigureSubscriptionUpdates(context.Context, *ConfigureSubscriptionUpdatesRequest) (*SubscriptionView, error)
	UpdateSubscription(context.Context, *SubscriptionId) (*SubscriptionUpdateResult, error)
	GetResolvedEndpoints(context.Context, *ResolvedEndpointsRequest) (*ResolvedEndpoints, error)
	SubscribeSubscriptionEvents(*emptypb.Empty, grpc.ServerStreamingServer[SubscriptionEvent]) error
	GetNodePool(context.Context, *emptypb.Empty) (*NodePool, error)
	SelectNode(context.Context, *SelectNodeRequest) (*SelectNodeResponse, error)
	GetProxyStatus(context.Context, *emptypb.Empty) (*ProxyStatus, error)
	GetRuntimeConfig(context.Context, *emptypb.Empty) (*RuntimeConfig, error)
	UpdateRuntimeConfig(context.Context, *UpdateRuntimeConfigRequest) (*RuntimeConfig, error)
	GetIpInfo(context.Context, *emptypb.Empty) (*IpInfoResponse, error)
	// Layer 2: Rule-based Routing
	UpsertRoute(context.Context, *UpsertRouteRequest) (*RouteInfo, error)
	DeleteRoute(context.Context, *DeleteRouteRequest) (*emptypb.Empty, error)
	ListRoutes(context.Context, *emptypb.Empty) (*RouteList, error)
	SelectRouteNode(context.Context, *SelectRouteNodeRequest) (*SelectNodeResponse, error)
	mustEmbedUnimplementedTargetLibServer()
}

// UnimplementedTargetLibServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTargetLibServer struct{}

func (UnimplementedTargetLibServer) Start(context.Context, *emptypb.Empty) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedTargetLibServer) Restart(context.Context, *emptypb.Empty) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Restart not implemented")
}
func (UnimplementedTargetLibServer) Stop(context.Context, *emptypb.Empty) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedTargetLibServer) GetState(context.Context, *emptypb.Empty) (*ServiceState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedTargetLibServer) SubscribeState(*emptypb.Empty, grpc.ServerStreamingServer[ServiceState]) error {
	return status.Error(codes.Unimplemented, "method SubscribeState not implemented")
}
func (UnimplementedTargetLibServer) SubscribeLogs(*emptypb.Empty, grpc.ServerStreamingServer[LogBatch]) error {
	return status.Error(codes.Unimplemented, "method SubscribeLogs not implemented")
}
func (UnimplementedTargetLibServer) SubscribeTraffic(*TrafficRequest, grpc.ServerStreamingServer[TrafficStatus]) error {
	return status.Error(codes.Unimplemented, "method SubscribeTraffic not implemented")
}
func (UnimplementedTargetLibServer) CloseConnection(context.Context, *CloseConnectionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseConnection not implemented")
}
func (UnimplementedTargetLibServer) CloseAllConnections(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseAllConnections not implemented")
}
func (UnimplementedTargetLibServer) ListSubscriptions(context.Context, *emptypb.Empty) (*SubscriptionList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSubscriptions not implemented")
}
func (UnimplementedTargetLibServer) GetSubscription(context.Context, *SubscriptionId) (*SubscriptionView, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubscription not implemented")
}
func (UnimplementedTargetLibServer) AddSubscription(context.Context, *AddSubscriptionRequest) (*SubscriptionView, error) {
	return nil, status.Error(codes.Unimplemented, "method AddSubscription not implemented")
}
func (UnimplementedTargetLibServer) RemoveSubscription(context.Context, *SubscriptionId) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveSubscription not implemented")
}
func (UnimplementedTargetLibServer) RenameSubscription(context.Context, *RenameSubscriptionRequest) (*SubscriptionView, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameSubscription not implemented")
}
func (UnimplementedTargetLibServer) SetSubscriptionEnabled(context.Context, *SetSubscriptionEnabledRequest) (*SubscriptionView, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSubscriptionEnabled not implemented")
}
func (UnimplementedTargetLibServer) ConfigureSubscriptionUpdates(context.Context, *ConfigureSubscriptionUpdatesRequest) (*SubscriptionView, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureSubscriptionUpdates not implemented")
}
func (UnimplementedTargetLibServer) UpdateSubscription(context.Context, *SubscriptionId) (*SubscriptionUpdateResult, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSubscription not implemented")
}
func (UnimplementedTargetLibServer) GetResolvedEndpoints(context.Context, *ResolvedEndpointsRequest) (*ResolvedEndpoints, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResolvedEndpoints not implemented")
}
func (UnimplementedTargetLibServer) SubscribeSubscriptionEvents(*emptypb.Empty, grpc.ServerStreamingServer[SubscriptionEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeSubscriptionEvents not implemented")
}
func (UnimplementedTargetLibServer) GetNodePool(context.Context, *emptypb.Empty) (*NodePool, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodePool not implemented")
}
func (UnimplementedTargetLibServer) SelectNode(context.Context, *SelectNodeRequest) (*SelectNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SelectNode not implemented")
}
func (UnimplementedTargetLibServer) GetProxyStatus(context.Context, *emptypb.Empty) (*ProxyStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProxyStatus not implemented")
}
func (UnimplementedTargetLibServer) GetRuntimeConfig(context.Context, *emptypb.Empty) (*RuntimeConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRuntimeConfig not implemented")
}
func (UnimplementedTargetLibServer) UpdateRuntimeConfig(context.Context, *UpdateRuntimeConfigRequest) (*RuntimeConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRuntimeConfig not implemented")
}
func (UnimplementedTargetLibServer) GetIpInfo(context.Context, *emptypb.Empty) (*IpInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIpInfo not implemented")
}
func (UnimplementedTargetLibServer) UpsertRoute(context.Context, *UpsertRouteRequest) (*RouteInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertRoute not implemented")
}
func (UnimplementedTargetLibServer) DeleteRoute(context.Context, *DeleteRouteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRoute not implemented")
}
func (UnimplementedTargetLibServer) ListRoutes(context.Context, *emptypb.Empty) (*RouteList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoutes not implemented")
}
func (UnimplementedTargetLibServer) SelectRouteNode(context.Context, *SelectRouteNodeRequest) (*SelectNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SelectRouteNode not implemented")
}
func (UnimplementedTargetLibServer) mustEmbedUnimplementedTargetLibServer() {}
func (UnimplementedTargetLibServer) testEmbeddedByValue()                   {}

// UnsafeTargetLibServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TargetLibServer will
// result in compilation errors.
type UnsafeTargetLibServer interface {
	mustEmbedUnimplementedTargetLibServer()
}

func RegisterTargetLibServer(s grpc.ServiceRegistrar, srv TargetLibServer) {
	// If the following call panics, it indicates UnimplementedTargetLibServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TargetLib_ServiceDesc, srv)
}

func _TargetLib_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).Start(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_Restart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).Restart(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).Stop(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).GetState(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_SubscribeState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TargetLibServer).SubscribeState(m, &grpc.GenericServerStream[emptypb.Empty, ServiceState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TargetLib_SubscribeStateServer = grpc.ServerStreamingServer[ServiceState]

func _TargetLib_SubscribeLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TargetLibServer).SubscribeLogs(m, &grpc.GenericServerStream[emptypb.Empty, LogBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TargetLib_SubscribeLogsServer = grpc.ServerStreamingServer[LogBatch]

func _TargetLib_SubscribeTraffic_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TrafficRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TargetLibServer).SubscribeTraffic(m, &grpc.GenericServerStream[TrafficRequest, TrafficStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TargetLib_SubscribeTrafficServer = grpc.ServerStreamingServer[TrafficStatus]

func _TargetLib_CloseConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).CloseConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_CloseConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).CloseConnection(ctx, req.(*CloseConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_CloseAllConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).CloseAllConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_CloseAllConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).CloseAllConnections(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_ListSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).ListSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_ListSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).ListSubscriptions(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_GetSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).GetSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_GetSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).GetSubscription(ctx, req.(*SubscriptionId))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_AddSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).AddSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_AddSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).AddSubscription(ctx, req.(*AddSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_RemoveSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).RemoveSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_RemoveSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).RemoveSubscription(ctx, req.(*SubscriptionId))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_RenameSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).RenameSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_RenameSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).RenameSubscription(ctx, req.(*RenameSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_SetSubscriptionEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSubscriptionEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).SetSubscriptionEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_SetSubscriptionEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).SetSubscriptionEnabled(ctx, req.(*SetSubscriptionEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_ConfigureSubscriptionUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureSubscriptionUpdatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).ConfigureSubscriptionUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_ConfigureSubscriptionUpdates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).ConfigureSubscriptionUpdates(ctx, req.(*ConfigureSubscriptionUpdatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_UpdateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).UpdateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_UpdateSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).UpdateSubscription(ctx, req.(*SubscriptionId))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_GetResolvedEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolvedEndpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).GetResolvedEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_GetResolvedEndpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).GetResolvedEndpoints(ctx, req.(*ResolvedEndpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_SubscribeSubscriptionEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TargetLibServer).SubscribeSubscriptionEvents(m, &grpc.GenericServerStream[emptypb.Empty, SubscriptionEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TargetLib_SubscribeSubscriptionEventsServer = grpc.ServerStreamingServer[SubscriptionEvent]

func _TargetLib_GetNodePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).GetNodePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_GetNodePool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).GetNodePool(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_SelectNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).SelectNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_SelectNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).SelectNode(ctx, req.(*SelectNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_GetProxyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).GetProxyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_GetProxyStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).GetProxyStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_GetRuntimeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).GetRuntimeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_GetRuntimeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).GetRuntimeConfig(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_UpdateRuntimeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRuntimeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).UpdateRuntimeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_UpdateRuntimeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).UpdateRuntimeConfig(ctx, req.(*UpdateRuntimeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_GetIpInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).GetIpInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_GetIpInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).GetIpInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_UpsertRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).UpsertRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_UpsertRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).UpsertRoute(ctx, req.(*UpsertRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_DeleteRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).DeleteRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_DeleteRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).DeleteRoute(ctx, req.(*DeleteRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_ListRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).ListRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_ListRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).ListRoutes(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_SelectRouteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectRouteNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).SelectRouteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_SelectRouteNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).SelectRouteNode(ctx, req.(*SelectRouteNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TargetLib_ServiceDesc is the grpc.ServiceDesc for TargetLib service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TargetLib_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "targetlib.TargetLib",
	HandlerType: (*TargetLibServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _TargetLib_Start_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _TargetLib_Restart_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _TargetLib_Stop_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _TargetLib_GetState_Handler,
		},
		{
			MethodName: "CloseConnection",
			Handler:    _TargetLib_CloseConnection_Handler,
		},
		{
			MethodName: "CloseAllConnections",
			Handler:    _TargetLib_CloseAllConnections_Handler,
		},
		{
			MethodName: "ListSubscriptions",
			Handler:    _TargetLib_ListSubscriptions_Handler,
		},
		{
			MethodName: "GetSubscription",
			Handler:    _TargetLib_GetSubscription_Handler,
		},
		{
			MethodName: "AddSubscription",
			Handler:    _TargetLib_AddSubscription_Handler,
		},
		{
			MethodName: "RemoveSubscription",
			Handler:    _TargetLib_RemoveSubscription_Handler,
		},
		{
			MethodName: "RenameSubscription",
			Handler:    _TargetLib_RenameSubscription_Handler,
		},
		{
			MethodName: "SetSubscriptionEnabled",
			Handler:    _TargetLib_SetSubscriptionEnabled_Handler,
		},
		{
			MethodName: "ConfigureSubscriptionUpdates",
			Handler:    _TargetLib_ConfigureSubscriptionUpdates_Handler,
		},
		{
			MethodName: "UpdateSubscription",
			Handler:    _TargetLib_UpdateSubscription_Handler,
		},
		{
			MethodName: "GetResolvedEndpoints",
			Handler:    _TargetLib_GetResolvedEndpoints_Handler,
		},
		{
			MethodName: "GetNodePool",
			Handler:    _TargetLib_GetNodePool_Handler,
		},
		{
			MethodName: "SelectNode",
			Handler:    _TargetLib_SelectNode_Handler,
		},
		{
			MethodName: "GetProxyStatus",
			Handler:    _TargetLib_GetProxyStatus_Handler,
		},
		{
			MethodName: "GetRuntimeConfig",
			Handler:    _TargetLib_GetRuntimeConfig_Handler,
		},
		{
			MethodName: "UpdateRuntimeConfig",
			Handler:    _TargetLib_UpdateRuntimeConfig_Handler,
		},
		{
			MethodName: "GetIpInfo",
			Handler:    _TargetLib_GetIpInfo_Handler,
		},
		{
			MethodName: "UpsertRoute",
			Handler:    _TargetLib_UpsertRoute_Handler,
		},
		{
			MethodName: "DeleteRoute",
			Handler:    _TargetLib_DeleteRoute_Handler,
		},
		{
			MethodName: "ListRoutes",
			Handler:    _TargetLib_ListRoutes_Handler,
		},
		{
			MethodName: "SelectRouteNode",
			Handler:    _TargetLib_SelectRouteNode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeState",
			Handler:       _TargetLib_SubscribeState_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeLogs",
			Handler:       _TargetLib_SubscribeLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeTraffic",
			Handler:       _TargetLib_SubscribeTraffic_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeSubscriptionEvents",
			Handler:       _TargetLib_SubscribeSubscriptionEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/TargetLib/targetlib.proto",
}
