// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/TargetLib/targetlib.proto

package targetlib

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TargetLib_GetVersion_FullMethodName                   = "/targetlib.TargetLib/GetVersion"
	TargetLib_GetCapabilities_FullMethodName              = "/targetlib.TargetLib/GetCapabilities"
	TargetLib_CheckConfig_FullMethodName                  = "/targetlib.TargetLib/CheckConfig"
	TargetLib_Start_FullMethodName                        = "/targetlib.TargetLib/Start"
	TargetLib_Reload_FullMethodName                       = "/targetlib.TargetLib/Reload"
	TargetLib_Restart_FullMethodName                      = "/targetlib.TargetLib/Restart"
	TargetLib_Stop_FullMethodName                         = "/targetlib.TargetLib/Stop"
	TargetLib_GetState_FullMethodName                     = "/targetlib.TargetLib/GetState"
	TargetLib_SubscribeState_FullMethodName               = "/targetlib.TargetLib/SubscribeState"
	TargetLib_SubscribeLogs_FullMethodName                = "/targetlib.TargetLib/SubscribeLogs"
	TargetLib_SelectOutbound_FullMethodName               = "/targetlib.TargetLib/SelectOutbound"
	TargetLib_CloseConnection_FullMethodName              = "/targetlib.TargetLib/CloseConnection"
	TargetLib_CloseAllConnections_FullMethodName          = "/targetlib.TargetLib/CloseAllConnections"
	TargetLib_ListSubscriptions_FullMethodName            = "/targetlib.TargetLib/ListSubscriptions"
	TargetLib_GetSubscription_FullMethodName              = "/targetlib.TargetLib/GetSubscription"
	TargetLib_AddSubscription_FullMethodName              = "/targetlib.TargetLib/AddSubscription"
	TargetLib_RemoveSubscription_FullMethodName           = "/targetlib.TargetLib/RemoveSubscription"
	TargetLib_RenameSubscription_FullMethodName           = "/targetlib.TargetLib/RenameSubscription"
	TargetLib_SetSubscriptionEnabled_FullMethodName       = "/targetlib.TargetLib/SetSubscriptionEnabled"
	TargetLib_ConfigureSubscriptionUpdates_FullMethodName = "/targetlib.TargetLib/ConfigureSubscriptionUpdates"
	TargetLib_UpdateSubscription_FullMethodName           = "/targetlib.TargetLib/UpdateSubscription"
	TargetLib_GetSubscriptionConfig_FullMethodName        = "/targetlib.TargetLib/GetSubscriptionConfig"
	TargetLib_BuildConfig_FullMethodName                  = "/targetlib.TargetLib/BuildConfig"
	TargetLib_ApplyRuntimeSettings_FullMethodName         = "/targetlib.TargetLib/ApplyRuntimeSettings"
	TargetLib_TestOutbound_FullMethodName                 = "/targetlib.TargetLib/TestOutbound"
	TargetLib_TestOutbounds_FullMethodName                = "/targetlib.TargetLib/TestOutbounds"
	TargetLib_GetResolvedEndpoints_FullMethodName         = "/targetlib.TargetLib/GetResolvedEndpoints"
	TargetLib_SubscribeSubscriptionEvents_FullMethodName  = "/targetlib.TargetLib/SubscribeSubscriptionEvents"
	TargetLib_SetActiveSubscription_FullMethodName        = "/targetlib.TargetLib/SetActiveSubscription"
	TargetLib_GetActiveSubscription_FullMethodName        = "/targetlib.TargetLib/GetActiveSubscription"
	TargetLib_GetIpInfo_FullMethodName                    = "/targetlib.TargetLib/GetIpInfo"
)

// TargetLibClient is the client API for TargetLib service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TargetLibClient interface {
	GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
	GetCapabilities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
	CheckConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*CheckConfigResponse, error)
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	Stop(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OperationResponse, error)
	GetState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServiceState, error)
	SubscribeState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceState], error)
	SubscribeLogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogBatch], error)
	SelectOutbound(ctx context.Context, in *SelectOutboundRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CloseConnection(ctx context.Context, in *CloseConnectionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CloseAllConnections(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListSubscriptions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SubscriptionList, error)
	GetSubscription(ctx context.Context, in *SubscriptionId, opts ...grpc.CallOption) (*SubscriptionView, error)
	AddSubscription(ctx context.Context, in *AddSubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionView, error)
	RemoveSubscription(ctx context.Context, in *SubscriptionId, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RenameSubscription(ctx context.Context, in *RenameSubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionView, error)
	SetSubscriptionEnabled(ctx context.Context, in *SetSubscriptionEnabledRequest, opts ...grpc.CallOption) (*SubscriptionView, error)
	ConfigureSubscriptionUpdates(ctx context.Context, in *ConfigureSubscriptionUpdatesRequest, opts ...grpc.CallOption) (*SubscriptionView, error)
	UpdateSubscription(ctx context.Context, in *SubscriptionId, opts ...grpc.CallOption) (*SubscriptionUpdateResult, error)
	GetSubscriptionConfig(ctx context.Context, in *SubscriptionId, opts ...grpc.CallOption) (*SubscriptionConfig, error)
	BuildConfig(ctx context.Context, in *BuildConfigRequest, opts ...grpc.CallOption) (*SubscriptionConfig, error)
	// Atomically builds, validates, and applies a runtime configuration. When
	// the service is already running, a failed reload restores the last known
	// good configuration before returning an error.
	ApplyRuntimeSettings(ctx context.Context, in *BuildConfigRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	TestOutbound(ctx context.Context, in *TestOutboundRequest, opts ...grpc.CallOption) (*LatencyTestResult, error)
	TestOutbounds(ctx context.Context, in *TestOutboundsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LatencyTestResult], error)
	GetResolvedEndpoints(ctx context.Context, in *ResolvedEndpointsRequest, opts ...grpc.CallOption) (*ResolvedEndpoints, error)
	SubscribeSubscriptionEvents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscriptionEvent], error)
	// Active subscription state is persisted by the backend; clients do not track it.
	SetActiveSubscription(ctx context.Context, in *SetActiveSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetActiveSubscription(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ActiveSubscriptionResponse, error)
	// IP geolocation query (egress from the backend).
	GetIpInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*IpInfoResponse, error)
}

type targetLibClient struct {
	cc grpc.ClientConnInterface
}

func NewTargetLibClient(cc grpc.ClientConnInterface) TargetLibClient {
	return &targetLibClient{cc}
}

func (c *targetLibClient) GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, TargetLib_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) GetCapabilities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, TargetLib_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) CheckConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*CheckConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckConfigResponse)
	err := c.cc.Invoke(ctx, TargetLib_CheckConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, TargetLib_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, TargetLib_Reload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, TargetLib_Restart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) Stop(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, TargetLib_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) GetState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServiceState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceState)
	err := c.cc.Invoke(ctx, TargetLib_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) SubscribeState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TargetLib_ServiceDesc.Streams[0], TargetLib_SubscribeState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, ServiceState]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TargetLib_SubscribeStateClient = grpc.ServerStreamingClient[ServiceState]

func (c *targetLibClient) SubscribeLogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TargetLib_ServiceDesc.Streams[1], TargetLib_SubscribeLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, LogBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TargetLib_SubscribeLogsClient = grpc.ServerStreamingClient[LogBatch]

func (c *targetLibClient) SelectOutbound(ctx context.Context, in *SelectOutboundRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TargetLib_SelectOutbound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) CloseConnection(ctx context.Context, in *CloseConnectionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TargetLib_CloseConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) CloseAllConnections(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TargetLib_CloseAllConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) ListSubscriptions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SubscriptionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionList)
	err := c.cc.Invoke(ctx, TargetLib_ListSubscriptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) GetSubscription(ctx context.Context, in *SubscriptionId, opts ...grpc.CallOption) (*SubscriptionView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionView)
	err := c.cc.Invoke(ctx, TargetLib_GetSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) AddSubscription(ctx context.Context, in *AddSubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionView)
	err := c.cc.Invoke(ctx, TargetLib_AddSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) RemoveSubscription(ctx context.Context, in *SubscriptionId, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TargetLib_RemoveSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) RenameSubscription(ctx context.Context, in *RenameSubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionView)
	err := c.cc.Invoke(ctx, TargetLib_RenameSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) SetSubscriptionEnabled(ctx context.Context, in *SetSubscriptionEnabledRequest, opts ...grpc.CallOption) (*SubscriptionView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionView)
	err := c.cc.Invoke(ctx, TargetLib_SetSubscriptionEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) ConfigureSubscriptionUpdates(ctx context.Context, in *ConfigureSubscriptionUpdatesRequest, opts ...grpc.CallOption) (*SubscriptionView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionView)
	err := c.cc.Invoke(ctx, TargetLib_ConfigureSubscriptionUpdates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) UpdateSubscription(ctx context.Context, in *SubscriptionId, opts ...grpc.CallOption) (*SubscriptionUpdateResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionUpdateResult)
	err := c.cc.Invoke(ctx, TargetLib_UpdateSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) GetSubscriptionConfig(ctx context.Context, in *SubscriptionId, opts ...grpc.CallOption) (*SubscriptionConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionConfig)
	err := c.cc.Invoke(ctx, TargetLib_GetSubscriptionConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) BuildConfig(ctx context.Context, in *BuildConfigRequest, opts ...grpc.CallOption) (*SubscriptionConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionConfig)
	err := c.cc.Invoke(ctx, TargetLib_BuildConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) ApplyRuntimeSettings(ctx context.Context, in *BuildConfigRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, TargetLib_ApplyRuntimeSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) TestOutbound(ctx context.Context, in *TestOutboundRequest, opts ...grpc.CallOption) (*LatencyTestResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LatencyTestResult)
	err := c.cc.Invoke(ctx, TargetLib_TestOutbound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) TestOutbounds(ctx context.Context, in *TestOutboundsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LatencyTestResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TargetLib_ServiceDesc.Streams[2], TargetLib_TestOutbounds_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TestOutboundsRequest, LatencyTestResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TargetLib_TestOutboundsClient = grpc.ServerStreamingClient[LatencyTestResult]

func (c *targetLibClient) GetResolvedEndpoints(ctx context.Context, in *ResolvedEndpointsRequest, opts ...grpc.CallOption) (*ResolvedEndpoints, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolvedEndpoints)
	err := c.cc.Invoke(ctx, TargetLib_GetResolvedEndpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) SubscribeSubscriptionEvents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscriptionEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TargetLib_ServiceDesc.Streams[3], TargetLib_SubscribeSubscriptionEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, SubscriptionEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TargetLib_SubscribeSubscriptionEventsClient = grpc.ServerStreamingClient[SubscriptionEvent]

func (c *targetLibClient) SetActiveSubscription(ctx context.Context, in *SetActiveSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TargetLib_SetActiveSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) GetActiveSubscription(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ActiveSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActiveSubscriptionResponse)
	err := c.cc.Invoke(ctx, TargetLib_GetActiveSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetLibClient) GetIpInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*IpInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IpInfoResponse)
	err := c.cc.Invoke(ctx, TargetLib_GetIpInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TargetLibServer is the server API for TargetLib service.
// All implementations must embed UnimplementedTargetLibServer
// for forward compatibility.
type TargetLibServer interface {
	GetVersion(context.Context, *emptypb.Empty) (*VersionResponse, error)
	GetCapabilities(context.Context, *emptypb.Empty) (*CapabilitiesResponse, error)
	CheckConfig(context.Context, *ConfigRequest) (*CheckConfigResponse, error)
	Start(context.Context, *StartRequest) (*OperationResponse, error)
	Reload(context.Context, *ReloadRequest) (*OperationResponse, error)
	Restart(context.Context, *RestartRequest) (*OperationResponse, error)
	Stop(context.Context, *emptypb.Empty) (*OperationResponse, error)
	GetState(context.Context, *emptypb.Empty) (*ServiceState, error)
	SubscribeState(*emptypb.Empty, grpc.ServerStreamingServer[ServiceState]) error
	SubscribeLogs(*emptypb.Empty, grpc.ServerStreamingServer[LogBatch]) error
	SelectOutbound(context.Context, *SelectOutboundRequest) (*emptypb.Empty, error)
	CloseConnection(context.Context, *CloseConnectionRequest) (*emptypb.Empty, error)
	CloseAllConnections(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	ListSubscriptions(context.Context, *emptypb.Empty) (*SubscriptionList, error)
	GetSubscription(context.Context, *SubscriptionId) (*SubscriptionView, error)
	AddSubscription(context.Context, *AddSubscriptionRequest) (*SubscriptionView, error)
	RemoveSubscription(context.Context, *SubscriptionId) (*emptypb.Empty, error)
	RenameSubscription(context.Context, *RenameSubscriptionRequest) (*SubscriptionView, error)
	SetSubscriptionEnabled(context.Context, *SetSubscriptionEnabledRequest) (*SubscriptionView, error)
	ConfigureSubscriptionUpdates(context.Context, *ConfigureSubscriptionUpdatesRequest) (*SubscriptionView, error)
	UpdateSubscription(context.Context, *SubscriptionId) (*SubscriptionUpdateResult, error)
	GetSubscriptionConfig(context.Context, *SubscriptionId) (*SubscriptionConfig, error)
	BuildConfig(context.Context, *BuildConfigRequest) (*SubscriptionConfig, error)
	// Atomically builds, validates, and applies a runtime configuration. When
	// the service is already running, a failed reload restores the last known
	// good configuration before returning an error.
	ApplyRuntimeSettings(context.Context, *BuildConfigRequest) (*OperationResponse, error)
	TestOutbound(context.Context, *TestOutboundRequest) (*LatencyTestResult, error)
	TestOutbounds(*TestOutboundsRequest, grpc.ServerStreamingServer[LatencyTestResult]) error
	GetResolvedEndpoints(context.Context, *ResolvedEndpointsRequest) (*ResolvedEndpoints, error)
	SubscribeSubscriptionEvents(*emptypb.Empty, grpc.ServerStreamingServer[SubscriptionEvent]) error
	// Active subscription state is persisted by the backend; clients do not track it.
	SetActiveSubscription(context.Context, *SetActiveSubscriptionRequest) (*emptypb.Empty, error)
	GetActiveSubscription(context.Context, *emptypb.Empty) (*ActiveSubscriptionResponse, error)
	// IP geolocation query (egress from the backend).
	GetIpInfo(context.Context, *emptypb.Empty) (*IpInfoResponse, error)
	mustEmbedUnimplementedTargetLibServer()
}

// UnimplementedTargetLibServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTargetLibServer struct{}

func (UnimplementedTargetLibServer) GetVersion(context.Context, *emptypb.Empty) (*VersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedTargetLibServer) GetCapabilities(context.Context, *emptypb.Empty) (*CapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedTargetLibServer) CheckConfig(context.Context, *ConfigRequest) (*CheckConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckConfig not implemented")
}
func (UnimplementedTargetLibServer) Start(context.Context, *StartRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedTargetLibServer) Reload(context.Context, *ReloadRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reload not implemented")
}
func (UnimplementedTargetLibServer) Restart(context.Context, *RestartRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Restart not implemented")
}
func (UnimplementedTargetLibServer) Stop(context.Context, *emptypb.Empty) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedTargetLibServer) GetState(context.Context, *emptypb.Empty) (*ServiceState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedTargetLibServer) SubscribeState(*emptypb.Empty, grpc.ServerStreamingServer[ServiceState]) error {
	return status.Error(codes.Unimplemented, "method SubscribeState not implemented")
}
func (UnimplementedTargetLibServer) SubscribeLogs(*emptypb.Empty, grpc.ServerStreamingServer[LogBatch]) error {
	return status.Error(codes.Unimplemented, "method SubscribeLogs not implemented")
}
func (UnimplementedTargetLibServer) SelectOutbound(context.Context, *SelectOutboundRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SelectOutbound not implemented")
}
func (UnimplementedTargetLibServer) CloseConnection(context.Context, *CloseConnectionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseConnection not implemented")
}
func (UnimplementedTargetLibServer) CloseAllConnections(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseAllConnections not implemented")
}
func (UnimplementedTargetLibServer) ListSubscriptions(context.Context, *emptypb.Empty) (*SubscriptionList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSubscriptions not implemented")
}
func (UnimplementedTargetLibServer) GetSubscription(context.Context, *SubscriptionId) (*SubscriptionView, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubscription not implemented")
}
func (UnimplementedTargetLibServer) AddSubscription(context.Context, *AddSubscriptionRequest) (*SubscriptionView, error) {
	return nil, status.Error(codes.Unimplemented, "method AddSubscription not implemented")
}
func (UnimplementedTargetLibServer) RemoveSubscription(context.Context, *SubscriptionId) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveSubscription not implemented")
}
func (UnimplementedTargetLibServer) RenameSubscription(context.Context, *RenameSubscriptionRequest) (*SubscriptionView, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameSubscription not implemented")
}
func (UnimplementedTargetLibServer) SetSubscriptionEnabled(context.Context, *SetSubscriptionEnabledRequest) (*SubscriptionView, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSubscriptionEnabled not implemented")
}
func (UnimplementedTargetLibServer) ConfigureSubscriptionUpdates(context.Context, *ConfigureSubscriptionUpdatesRequest) (*SubscriptionView, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureSubscriptionUpdates not implemented")
}
func (UnimplementedTargetLibServer) UpdateSubscription(context.Context, *SubscriptionId) (*SubscriptionUpdateResult, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSubscription not implemented")
}
func (UnimplementedTargetLibServer) GetSubscriptionConfig(context.Context, *SubscriptionId) (*SubscriptionConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubscriptionConfig not implemented")
}
func (UnimplementedTargetLibServer) BuildConfig(context.Context, *BuildConfigRequest) (*SubscriptionConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildConfig not implemented")
}
func (UnimplementedTargetLibServer) ApplyRuntimeSettings(context.Context, *BuildConfigRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyRuntimeSettings not implemented")
}
func (UnimplementedTargetLibServer) TestOutbound(context.Context, *TestOutboundRequest) (*LatencyTestResult, error) {
	return nil, status.Error(codes.Unimplemented, "method TestOutbound not implemented")
}
func (UnimplementedTargetLibServer) TestOutbounds(*TestOutboundsRequest, grpc.ServerStreamingServer[LatencyTestResult]) error {
	return status.Error(codes.Unimplemented, "method TestOutbounds not implemented")
}
func (UnimplementedTargetLibServer) GetResolvedEndpoints(context.Context, *ResolvedEndpointsRequest) (*ResolvedEndpoints, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResolvedEndpoints not implemented")
}
func (UnimplementedTargetLibServer) SubscribeSubscriptionEvents(*emptypb.Empty, grpc.ServerStreamingServer[SubscriptionEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeSubscriptionEvents not implemented")
}
func (UnimplementedTargetLibServer) SetActiveSubscription(context.Context, *SetActiveSubscriptionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetActiveSubscription not implemented")
}
func (UnimplementedTargetLibServer) GetActiveSubscription(context.Context, *emptypb.Empty) (*ActiveSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveSubscription not implemented")
}
func (UnimplementedTargetLibServer) GetIpInfo(context.Context, *emptypb.Empty) (*IpInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIpInfo not implemented")
}
func (UnimplementedTargetLibServer) mustEmbedUnimplementedTargetLibServer() {}
func (UnimplementedTargetLibServer) testEmbeddedByValue()                   {}

// UnsafeTargetLibServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TargetLibServer will
// result in compilation errors.
type UnsafeTargetLibServer interface {
	mustEmbedUnimplementedTargetLibServer()
}

func RegisterTargetLibServer(s grpc.ServiceRegistrar, srv TargetLibServer) {
	// If the following call panics, it indicates UnimplementedTargetLibServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TargetLib_ServiceDesc, srv)
}

func _TargetLib_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).GetVersion(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).GetCapabilities(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_CheckConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).CheckConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_CheckConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).CheckConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_Reload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).Reload(ctx, req.(*ReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_Restart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).Restart(ctx, req.(*RestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).Stop(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).GetState(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_SubscribeState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TargetLibServer).SubscribeState(m, &grpc.GenericServerStream[emptypb.Empty, ServiceState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TargetLib_SubscribeStateServer = grpc.ServerStreamingServer[ServiceState]

func _TargetLib_SubscribeLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TargetLibServer).SubscribeLogs(m, &grpc.GenericServerStream[emptypb.Empty, LogBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TargetLib_SubscribeLogsServer = grpc.ServerStreamingServer[LogBatch]

func _TargetLib_SelectOutbound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectOutboundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).SelectOutbound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_SelectOutbound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).SelectOutbound(ctx, req.(*SelectOutboundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_CloseConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).CloseConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_CloseConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).CloseConnection(ctx, req.(*CloseConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_CloseAllConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).CloseAllConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_CloseAllConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).CloseAllConnections(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_ListSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).ListSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_ListSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).ListSubscriptions(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_GetSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).GetSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_GetSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).GetSubscription(ctx, req.(*SubscriptionId))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_AddSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).AddSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_AddSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).AddSubscription(ctx, req.(*AddSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_RemoveSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).RemoveSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_RemoveSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).RemoveSubscription(ctx, req.(*SubscriptionId))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_RenameSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).RenameSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_RenameSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).RenameSubscription(ctx, req.(*RenameSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_SetSubscriptionEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSubscriptionEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).SetSubscriptionEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_SetSubscriptionEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).SetSubscriptionEnabled(ctx, req.(*SetSubscriptionEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_ConfigureSubscriptionUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureSubscriptionUpdatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).ConfigureSubscriptionUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_ConfigureSubscriptionUpdates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).ConfigureSubscriptionUpdates(ctx, req.(*ConfigureSubscriptionUpdatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_UpdateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).UpdateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_UpdateSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).UpdateSubscription(ctx, req.(*SubscriptionId))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_GetSubscriptionConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).GetSubscriptionConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_GetSubscriptionConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).GetSubscriptionConfig(ctx, req.(*SubscriptionId))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_BuildConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).BuildConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_BuildConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).BuildConfig(ctx, req.(*BuildConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_ApplyRuntimeSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).ApplyRuntimeSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_ApplyRuntimeSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).ApplyRuntimeSettings(ctx, req.(*BuildConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_TestOutbound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestOutboundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).TestOutbound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_TestOutbound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).TestOutbound(ctx, req.(*TestOutboundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_TestOutbounds_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TestOutboundsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TargetLibServer).TestOutbounds(m, &grpc.GenericServerStream[TestOutboundsRequest, LatencyTestResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TargetLib_TestOutboundsServer = grpc.ServerStreamingServer[LatencyTestResult]

func _TargetLib_GetResolvedEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolvedEndpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).GetResolvedEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_GetResolvedEndpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).GetResolvedEndpoints(ctx, req.(*ResolvedEndpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_SubscribeSubscriptionEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TargetLibServer).SubscribeSubscriptionEvents(m, &grpc.GenericServerStream[emptypb.Empty, SubscriptionEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TargetLib_SubscribeSubscriptionEventsServer = grpc.ServerStreamingServer[SubscriptionEvent]

func _TargetLib_SetActiveSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetActiveSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).SetActiveSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_SetActiveSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).SetActiveSubscription(ctx, req.(*SetActiveSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_GetActiveSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).GetActiveSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_GetActiveSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).GetActiveSubscription(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetLib_GetIpInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetLibServer).GetIpInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetLib_GetIpInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetLibServer).GetIpInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TargetLib_ServiceDesc is the grpc.ServiceDesc for TargetLib service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TargetLib_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "targetlib.TargetLib",
	HandlerType: (*TargetLibServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _TargetLib_GetVersion_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _TargetLib_GetCapabilities_Handler,
		},
		{
			MethodName: "CheckConfig",
			Handler:    _TargetLib_CheckConfig_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _TargetLib_Start_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _TargetLib_Reload_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _TargetLib_Restart_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _TargetLib_Stop_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _TargetLib_GetState_Handler,
		},
		{
			MethodName: "SelectOutbound",
			Handler:    _TargetLib_SelectOutbound_Handler,
		},
		{
			MethodName: "CloseConnection",
			Handler:    _TargetLib_CloseConnection_Handler,
		},
		{
			MethodName: "CloseAllConnections",
			Handler:    _TargetLib_CloseAllConnections_Handler,
		},
		{
			MethodName: "ListSubscriptions",
			Handler:    _TargetLib_ListSubscriptions_Handler,
		},
		{
			MethodName: "GetSubscription",
			Handler:    _TargetLib_GetSubscription_Handler,
		},
		{
			MethodName: "AddSubscription",
			Handler:    _TargetLib_AddSubscription_Handler,
		},
		{
			MethodName: "RemoveSubscription",
			Handler:    _TargetLib_RemoveSubscription_Handler,
		},
		{
			MethodName: "RenameSubscription",
			Handler:    _TargetLib_RenameSubscription_Handler,
		},
		{
			MethodName: "SetSubscriptionEnabled",
			Handler:    _TargetLib_SetSubscriptionEnabled_Handler,
		},
		{
			MethodName: "ConfigureSubscriptionUpdates",
			Handler:    _TargetLib_ConfigureSubscriptionUpdates_Handler,
		},
		{
			MethodName: "UpdateSubscription",
			Handler:    _TargetLib_UpdateSubscription_Handler,
		},
		{
			MethodName: "GetSubscriptionConfig",
			Handler:    _TargetLib_GetSubscriptionConfig_Handler,
		},
		{
			MethodName: "BuildConfig",
			Handler:    _TargetLib_BuildConfig_Handler,
		},
		{
			MethodName: "ApplyRuntimeSettings",
			Handler:    _TargetLib_ApplyRuntimeSettings_Handler,
		},
		{
			MethodName: "TestOutbound",
			Handler:    _TargetLib_TestOutbound_Handler,
		},
		{
			MethodName: "GetResolvedEndpoints",
			Handler:    _TargetLib_GetResolvedEndpoints_Handler,
		},
		{
			MethodName: "SetActiveSubscription",
			Handler:    _TargetLib_SetActiveSubscription_Handler,
		},
		{
			MethodName: "GetActiveSubscription",
			Handler:    _TargetLib_GetActiveSubscription_Handler,
		},
		{
			MethodName: "GetIpInfo",
			Handler:    _TargetLib_GetIpInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeState",
			Handler:       _TargetLib_SubscribeState_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeLogs",
			Handler:       _TargetLib_SubscribeLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TestOutbounds",
			Handler:       _TargetLib_TestOutbounds_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeSubscriptionEvents",
			Handler:       _TargetLib_SubscribeSubscriptionEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/TargetLib/targetlib.proto",
}
