// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/libbox/v1/manager.proto

package libboxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LibboxManager_GetVersion_FullMethodName      = "/libbox.v1.LibboxManager/GetVersion"
	LibboxManager_GetCapabilities_FullMethodName = "/libbox.v1.LibboxManager/GetCapabilities"
	LibboxManager_CheckConfig_FullMethodName     = "/libbox.v1.LibboxManager/CheckConfig"
	LibboxManager_Start_FullMethodName           = "/libbox.v1.LibboxManager/Start"
	LibboxManager_Reload_FullMethodName          = "/libbox.v1.LibboxManager/Reload"
	LibboxManager_Restart_FullMethodName         = "/libbox.v1.LibboxManager/Restart"
	LibboxManager_Stop_FullMethodName            = "/libbox.v1.LibboxManager/Stop"
	LibboxManager_GetState_FullMethodName        = "/libbox.v1.LibboxManager/GetState"
	LibboxManager_SubscribeState_FullMethodName  = "/libbox.v1.LibboxManager/SubscribeState"
)

// LibboxManagerClient is the client API for LibboxManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LibboxManagerClient interface {
	GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
	GetCapabilities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
	CheckConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*CheckConfigResponse, error)
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	Stop(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OperationResponse, error)
	GetState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServiceState, error)
	SubscribeState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceState], error)
}

type libboxManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewLibboxManagerClient(cc grpc.ClientConnInterface) LibboxManagerClient {
	return &libboxManagerClient{cc}
}

func (c *libboxManagerClient) GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, LibboxManager_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libboxManagerClient) GetCapabilities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, LibboxManager_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libboxManagerClient) CheckConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*CheckConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckConfigResponse)
	err := c.cc.Invoke(ctx, LibboxManager_CheckConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libboxManagerClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, LibboxManager_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libboxManagerClient) Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, LibboxManager_Reload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libboxManagerClient) Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, LibboxManager_Restart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libboxManagerClient) Stop(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, LibboxManager_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libboxManagerClient) GetState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServiceState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceState)
	err := c.cc.Invoke(ctx, LibboxManager_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libboxManagerClient) SubscribeState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LibboxManager_ServiceDesc.Streams[0], LibboxManager_SubscribeState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, ServiceState]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LibboxManager_SubscribeStateClient = grpc.ServerStreamingClient[ServiceState]

// LibboxManagerServer is the server API for LibboxManager service.
// All implementations must embed UnimplementedLibboxManagerServer
// for forward compatibility.
type LibboxManagerServer interface {
	GetVersion(context.Context, *emptypb.Empty) (*VersionResponse, error)
	GetCapabilities(context.Context, *emptypb.Empty) (*CapabilitiesResponse, error)
	CheckConfig(context.Context, *ConfigRequest) (*CheckConfigResponse, error)
	Start(context.Context, *StartRequest) (*OperationResponse, error)
	Reload(context.Context, *ReloadRequest) (*OperationResponse, error)
	Restart(context.Context, *RestartRequest) (*OperationResponse, error)
	Stop(context.Context, *emptypb.Empty) (*OperationResponse, error)
	GetState(context.Context, *emptypb.Empty) (*ServiceState, error)
	SubscribeState(*emptypb.Empty, grpc.ServerStreamingServer[ServiceState]) error
	mustEmbedUnimplementedLibboxManagerServer()
}

// UnimplementedLibboxManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLibboxManagerServer struct{}

func (UnimplementedLibboxManagerServer) GetVersion(context.Context, *emptypb.Empty) (*VersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedLibboxManagerServer) GetCapabilities(context.Context, *emptypb.Empty) (*CapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedLibboxManagerServer) CheckConfig(context.Context, *ConfigRequest) (*CheckConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckConfig not implemented")
}
func (UnimplementedLibboxManagerServer) Start(context.Context, *StartRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedLibboxManagerServer) Reload(context.Context, *ReloadRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reload not implemented")
}
func (UnimplementedLibboxManagerServer) Restart(context.Context, *RestartRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Restart not implemented")
}
func (UnimplementedLibboxManagerServer) Stop(context.Context, *emptypb.Empty) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedLibboxManagerServer) GetState(context.Context, *emptypb.Empty) (*ServiceState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedLibboxManagerServer) SubscribeState(*emptypb.Empty, grpc.ServerStreamingServer[ServiceState]) error {
	return status.Error(codes.Unimplemented, "method SubscribeState not implemented")
}
func (UnimplementedLibboxManagerServer) mustEmbedUnimplementedLibboxManagerServer() {}
func (UnimplementedLibboxManagerServer) testEmbeddedByValue()                       {}

// UnsafeLibboxManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LibboxManagerServer will
// result in compilation errors.
type UnsafeLibboxManagerServer interface {
	mustEmbedUnimplementedLibboxManagerServer()
}

func RegisterLibboxManagerServer(s grpc.ServiceRegistrar, srv LibboxManagerServer) {
	// If the following call panics, it indicates UnimplementedLibboxManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LibboxManager_ServiceDesc, srv)
}

func _LibboxManager_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibboxManagerServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibboxManager_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibboxManagerServer).GetVersion(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibboxManager_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibboxManagerServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibboxManager_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibboxManagerServer).GetCapabilities(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibboxManager_CheckConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibboxManagerServer).CheckConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibboxManager_CheckConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibboxManagerServer).CheckConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibboxManager_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibboxManagerServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibboxManager_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibboxManagerServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibboxManager_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibboxManagerServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibboxManager_Reload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibboxManagerServer).Reload(ctx, req.(*ReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibboxManager_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibboxManagerServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibboxManager_Restart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibboxManagerServer).Restart(ctx, req.(*RestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibboxManager_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibboxManagerServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibboxManager_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibboxManagerServer).Stop(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibboxManager_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibboxManagerServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibboxManager_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibboxManagerServer).GetState(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibboxManager_SubscribeState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LibboxManagerServer).SubscribeState(m, &grpc.GenericServerStream[emptypb.Empty, ServiceState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LibboxManager_SubscribeStateServer = grpc.ServerStreamingServer[ServiceState]

// LibboxManager_ServiceDesc is the grpc.ServiceDesc for LibboxManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LibboxManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "libbox.v1.LibboxManager",
	HandlerType: (*LibboxManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _LibboxManager_GetVersion_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _LibboxManager_GetCapabilities_Handler,
		},
		{
			MethodName: "CheckConfig",
			Handler:    _LibboxManager_CheckConfig_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _LibboxManager_Start_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _LibboxManager_Reload_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _LibboxManager_Restart_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _LibboxManager_Stop_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _LibboxManager_GetState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeState",
			Handler:       _LibboxManager_SubscribeState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/libbox/v1/manager.proto",
}
