// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/libbox/v1/manager.proto

package libboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceStateType int32

const (
	ServiceStateType_SERVICE_STATE_UNSPECIFIED ServiceStateType = 0
	ServiceStateType_SERVICE_STATE_IDLE        ServiceStateType = 1
	ServiceStateType_SERVICE_STATE_STARTING    ServiceStateType = 2
	ServiceStateType_SERVICE_STATE_RUNNING     ServiceStateType = 3
	ServiceStateType_SERVICE_STATE_STOPPING    ServiceStateType = 4
	ServiceStateType_SERVICE_STATE_FAILED      ServiceStateType = 5
)

// Enum value maps for ServiceStateType.
var (
	ServiceStateType_name = map[int32]string{
		0: "SERVICE_STATE_UNSPECIFIED",
		1: "SERVICE_STATE_IDLE",
		2: "SERVICE_STATE_STARTING",
		3: "SERVICE_STATE_RUNNING",
		4: "SERVICE_STATE_STOPPING",
		5: "SERVICE_STATE_FAILED",
	}
	ServiceStateType_value = map[string]int32{
		"SERVICE_STATE_UNSPECIFIED": 0,
		"SERVICE_STATE_IDLE":        1,
		"SERVICE_STATE_STARTING":    2,
		"SERVICE_STATE_RUNNING":     3,
		"SERVICE_STATE_STOPPING":    4,
		"SERVICE_STATE_FAILED":      5,
	}
)

func (x ServiceStateType) Enum() *ServiceStateType {
	p := new(ServiceStateType)
	*p = x
	return p
}

func (x ServiceStateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceStateType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_libbox_v1_manager_proto_enumTypes[0].Descriptor()
}

func (ServiceStateType) Type() protoreflect.EnumType {
	return &file_api_libbox_v1_manager_proto_enumTypes[0]
}

func (x ServiceStateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceStateType.Descriptor instead.
func (ServiceStateType) EnumDescriptor() ([]byte, []int) {
	return file_api_libbox_v1_manager_proto_rawDescGZIP(), []int{0}
}

type VersionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LibboxVersion   string                 `protobuf:"bytes,1,opt,name=libbox_version,json=libboxVersion,proto3" json:"libbox_version,omitempty"`
	SingBoxVersion  string                 `protobuf:"bytes,2,opt,name=sing_box_version,json=singBoxVersion,proto3" json:"sing_box_version,omitempty"`
	GoVersion       string                 `protobuf:"bytes,3,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	ProtocolVersion uint32                 `protobuf:"varint,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_api_libbox_v1_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_libbox_v1_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_api_libbox_v1_manager_proto_rawDescGZIP(), []int{0}
}

func (x *VersionResponse) GetLibboxVersion() string {
	if x != nil {
		return x.LibboxVersion
	}
	return ""
}

func (x *VersionResponse) GetSingBoxVersion() string {
	if x != nil {
		return x.SingBoxVersion
	}
	return ""
}

func (x *VersionResponse) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *VersionResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type CapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	SystemProxy   bool                   `protobuf:"varint,2,opt,name=system_proxy,json=systemProxy,proto3" json:"system_proxy,omitempty"`
	PlatformVpn   bool                   `protobuf:"varint,3,opt,name=platform_vpn,json=platformVpn,proto3" json:"platform_vpn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_api_libbox_v1_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_libbox_v1_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_api_libbox_v1_manager_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilitiesResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CapabilitiesResponse) GetSystemProxy() bool {
	if x != nil {
		return x.SystemProxy
	}
	return false
}

func (x *CapabilitiesResponse) GetPlatformVpn() bool {
	if x != nil {
		return x.PlatformVpn
	}
	return false
}

type ConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_api_libbox_v1_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_libbox_v1_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_libbox_v1_manager_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CheckConfigResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Valid          bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	FormattedError string                 `protobuf:"bytes,2,opt,name=formatted_error,json=formattedError,proto3" json:"formatted_error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckConfigResponse) Reset() {
	*x = CheckConfigResponse{}
	mi := &file_api_libbox_v1_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConfigResponse) ProtoMessage() {}

func (x *CheckConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_libbox_v1_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConfigResponse.ProtoReflect.Descriptor instead.
func (*CheckConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_libbox_v1_manager_proto_rawDescGZIP(), []int{3}
}

func (x *CheckConfigResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *CheckConfigResponse) GetFormattedError() string {
	if x != nil {
		return x.FormattedError
	}
	return ""
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_api_libbox_v1_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_libbox_v1_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_api_libbox_v1_manager_proto_rawDescGZIP(), []int{4}
}

func (x *StartRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type ReloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadRequest) Reset() {
	*x = ReloadRequest{}
	mi := &file_api_libbox_v1_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadRequest) ProtoMessage() {}

func (x *ReloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_libbox_v1_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadRequest.ProtoReflect.Descriptor instead.
func (*ReloadRequest) Descriptor() ([]byte, []int) {
	return file_api_libbox_v1_manager_proto_rawDescGZIP(), []int{5}
}

func (x *ReloadRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type RestartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartRequest) Reset() {
	*x = RestartRequest{}
	mi := &file_api_libbox_v1_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartRequest) ProtoMessage() {}

func (x *RestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_libbox_v1_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartRequest.ProtoReflect.Descriptor instead.
func (*RestartRequest) Descriptor() ([]byte, []int) {
	return file_api_libbox_v1_manager_proto_rawDescGZIP(), []int{6}
}

func (x *RestartRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type OperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *ServiceState          `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_api_libbox_v1_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_libbox_v1_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_api_libbox_v1_manager_proto_rawDescGZIP(), []int{7}
}

func (x *OperationResponse) GetState() *ServiceState {
	if x != nil {
		return x.State
	}
	return nil
}

type ServiceState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	State           ServiceStateType       `protobuf:"varint,1,opt,name=state,proto3,enum=libbox.v1.ServiceStateType" json:"state,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ChangedAtUnixMs int64                  `protobuf:"varint,3,opt,name=changed_at_unix_ms,json=changedAtUnixMs,proto3" json:"changed_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceState) Reset() {
	*x = ServiceState{}
	mi := &file_api_libbox_v1_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceState) ProtoMessage() {}

func (x *ServiceState) ProtoReflect() protoreflect.Message {
	mi := &file_api_libbox_v1_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceState.ProtoReflect.Descriptor instead.
func (*ServiceState) Descriptor() ([]byte, []int) {
	return file_api_libbox_v1_manager_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceState) GetState() ServiceStateType {
	if x != nil {
		return x.State
	}
	return ServiceStateType_SERVICE_STATE_UNSPECIFIED
}

func (x *ServiceState) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ServiceState) GetChangedAtUnixMs() int64 {
	if x != nil {
		return x.ChangedAtUnixMs
	}
	return 0
}

type SystemProxyStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Supported     bool                   `protobuf:"varint,1,opt,name=supported,proto3" json:"supported,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Server        string                 `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	Bypass        string                 `protobuf:"bytes,4,opt,name=bypass,proto3" json:"bypass,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemProxyStatus) Reset() {
	*x = SystemProxyStatus{}
	mi := &file_api_libbox_v1_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemProxyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemProxyStatus) ProtoMessage() {}

func (x *SystemProxyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_libbox_v1_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemProxyStatus.ProtoReflect.Descriptor instead.
func (*SystemProxyStatus) Descriptor() ([]byte, []int) {
	return file_api_libbox_v1_manager_proto_rawDescGZIP(), []int{9}
}

func (x *SystemProxyStatus) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

func (x *SystemProxyStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SystemProxyStatus) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *SystemProxyStatus) GetBypass() string {
	if x != nil {
		return x.Bypass
	}
	return ""
}

type SetSystemProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Bypass        string                 `protobuf:"bytes,4,opt,name=bypass,proto3" json:"bypass,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSystemProxyRequest) Reset() {
	*x = SetSystemProxyRequest{}
	mi := &file_api_libbox_v1_manager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSystemProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSystemProxyRequest) ProtoMessage() {}

func (x *SetSystemProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_libbox_v1_manager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSystemProxyRequest.ProtoReflect.Descriptor instead.
func (*SetSystemProxyRequest) Descriptor() ([]byte, []int) {
	return file_api_libbox_v1_manager_proto_rawDescGZIP(), []int{10}
}

func (x *SetSystemProxyRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SetSystemProxyRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SetSystemProxyRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SetSystemProxyRequest) GetBypass() string {
	if x != nil {
		return x.Bypass
	}
	return ""
}

var File_api_libbox_v1_manager_proto protoreflect.FileDescriptor

const file_api_libbox_v1_manager_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/libbox/v1/manager.proto\x12\tlibbox.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xac\x01\n" +
	"\x0fVersionResponse\x12%\n" +
	"\x0elibbox_version\x18\x01 \x01(\tR\rlibboxVersion\x12(\n" +
	"\x10sing_box_version\x18\x02 \x01(\tR\x0esingBoxVersion\x12\x1d\n" +
	"\n" +
	"go_version\x18\x03 \x01(\tR\tgoVersion\x12)\n" +
	"\x10protocol_version\x18\x04 \x01(\rR\x0fprotocolVersion\"~\n" +
	"\x14CapabilitiesResponse\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12!\n" +
	"\fsystem_proxy\x18\x02 \x01(\bR\vsystemProxy\x12!\n" +
	"\fplatform_vpn\x18\x03 \x01(\bR\vplatformVpnJ\x04\b\x04\x10\x05\")\n" +
	"\rConfigRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"T\n" +
	"\x13CheckConfigResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12'\n" +
	"\x0fformatted_error\x18\x02 \x01(\tR\x0eformattedError\"&\n" +
	"\fStartRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\"'\n" +
	"\rReloadRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\"(\n" +
	"\x0eRestartRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\"B\n" +
	"\x11OperationResponse\x12-\n" +
	"\x05state\x18\x01 \x01(\v2\x17.libbox.v1.ServiceStateR\x05state\"\x93\x01\n" +
	"\fServiceState\x121\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1b.libbox.v1.ServiceStateTypeR\x05state\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12+\n" +
	"\x12changed_at_unix_ms\x18\x03 \x01(\x03R\x0fchangedAtUnixMs\"{\n" +
	"\x11SystemProxyStatus\x12\x1c\n" +
	"\tsupported\x18\x01 \x01(\bR\tsupported\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x16\n" +
	"\x06server\x18\x03 \x01(\tR\x06server\x12\x16\n" +
	"\x06bypass\x18\x04 \x01(\tR\x06bypass\"q\n" +
	"\x15SetSystemProxyRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x16\n" +
	"\x06bypass\x18\x04 \x01(\tR\x06bypass*\xb6\x01\n" +
	"\x10ServiceStateType\x12\x1d\n" +
	"\x19SERVICE_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SERVICE_STATE_IDLE\x10\x01\x12\x1a\n" +
	"\x16SERVICE_STATE_STARTING\x10\x02\x12\x19\n" +
	"\x15SERVICE_STATE_RUNNING\x10\x03\x12\x1a\n" +
	"\x16SERVICE_STATE_STOPPING\x10\x04\x12\x18\n" +
	"\x14SERVICE_STATE_FAILED\x10\x052\x8c\x06\n" +
	"\rLibboxManager\x12@\n" +
	"\n" +
	"GetVersion\x12\x16.google.protobuf.Empty\x1a\x1a.libbox.v1.VersionResponse\x12J\n" +
	"\x0fGetCapabilities\x12\x16.google.protobuf.Empty\x1a\x1f.libbox.v1.CapabilitiesResponse\x12G\n" +
	"\vCheckConfig\x12\x18.libbox.v1.ConfigRequest\x1a\x1e.libbox.v1.CheckConfigResponse\x12>\n" +
	"\x05Start\x12\x17.libbox.v1.StartRequest\x1a\x1c.libbox.v1.OperationResponse\x12@\n" +
	"\x06Reload\x12\x18.libbox.v1.ReloadRequest\x1a\x1c.libbox.v1.OperationResponse\x12B\n" +
	"\aRestart\x12\x19.libbox.v1.RestartRequest\x1a\x1c.libbox.v1.OperationResponse\x12<\n" +
	"\x04Stop\x12\x16.google.protobuf.Empty\x1a\x1c.libbox.v1.OperationResponse\x12;\n" +
	"\bGetState\x12\x16.google.protobuf.Empty\x1a\x17.libbox.v1.ServiceState\x12C\n" +
	"\x0eSubscribeState\x12\x16.google.protobuf.Empty\x1a\x17.libbox.v1.ServiceState0\x01\x12L\n" +
	"\x14GetSystemProxyStatus\x12\x16.google.protobuf.Empty\x1a\x1c.libbox.v1.SystemProxyStatus\x12P\n" +
	"\x0eSetSystemProxy\x12 .libbox.v1.SetSystemProxyRequest\x1a\x1c.libbox.v1.SystemProxyStatusB6Z4github.com/loafman1120/libbox/api/libbox/v1;libboxv1b\x06proto3"

var (
	file_api_libbox_v1_manager_proto_rawDescOnce sync.Once
	file_api_libbox_v1_manager_proto_rawDescData []byte
)

func file_api_libbox_v1_manager_proto_rawDescGZIP() []byte {
	file_api_libbox_v1_manager_proto_rawDescOnce.Do(func() {
		file_api_libbox_v1_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_libbox_v1_manager_proto_rawDesc), len(file_api_libbox_v1_manager_proto_rawDesc)))
	})
	return file_api_libbox_v1_manager_proto_rawDescData
}

var file_api_libbox_v1_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_libbox_v1_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_libbox_v1_manager_proto_goTypes = []any{
	(ServiceStateType)(0),         // 0: libbox.v1.ServiceStateType
	(*VersionResponse)(nil),       // 1: libbox.v1.VersionResponse
	(*CapabilitiesResponse)(nil),  // 2: libbox.v1.CapabilitiesResponse
	(*ConfigRequest)(nil),         // 3: libbox.v1.ConfigRequest
	(*CheckConfigResponse)(nil),   // 4: libbox.v1.CheckConfigResponse
	(*StartRequest)(nil),          // 5: libbox.v1.StartRequest
	(*ReloadRequest)(nil),         // 6: libbox.v1.ReloadRequest
	(*RestartRequest)(nil),        // 7: libbox.v1.RestartRequest
	(*OperationResponse)(nil),     // 8: libbox.v1.OperationResponse
	(*ServiceState)(nil),          // 9: libbox.v1.ServiceState
	(*SystemProxyStatus)(nil),     // 10: libbox.v1.SystemProxyStatus
	(*SetSystemProxyRequest)(nil), // 11: libbox.v1.SetSystemProxyRequest
	(*emptypb.Empty)(nil),         // 12: google.protobuf.Empty
}
var file_api_libbox_v1_manager_proto_depIdxs = []int32{
	9,  // 0: libbox.v1.OperationResponse.state:type_name -> libbox.v1.ServiceState
	0,  // 1: libbox.v1.ServiceState.state:type_name -> libbox.v1.ServiceStateType
	12, // 2: libbox.v1.LibboxManager.GetVersion:input_type -> google.protobuf.Empty
	12, // 3: libbox.v1.LibboxManager.GetCapabilities:input_type -> google.protobuf.Empty
	3,  // 4: libbox.v1.LibboxManager.CheckConfig:input_type -> libbox.v1.ConfigRequest
	5,  // 5: libbox.v1.LibboxManager.Start:input_type -> libbox.v1.StartRequest
	6,  // 6: libbox.v1.LibboxManager.Reload:input_type -> libbox.v1.ReloadRequest
	7,  // 7: libbox.v1.LibboxManager.Restart:input_type -> libbox.v1.RestartRequest
	12, // 8: libbox.v1.LibboxManager.Stop:input_type -> google.protobuf.Empty
	12, // 9: libbox.v1.LibboxManager.GetState:input_type -> google.protobuf.Empty
	12, // 10: libbox.v1.LibboxManager.SubscribeState:input_type -> google.protobuf.Empty
	12, // 11: libbox.v1.LibboxManager.GetSystemProxyStatus:input_type -> google.protobuf.Empty
	11, // 12: libbox.v1.LibboxManager.SetSystemProxy:input_type -> libbox.v1.SetSystemProxyRequest
	1,  // 13: libbox.v1.LibboxManager.GetVersion:output_type -> libbox.v1.VersionResponse
	2,  // 14: libbox.v1.LibboxManager.GetCapabilities:output_type -> libbox.v1.CapabilitiesResponse
	4,  // 15: libbox.v1.LibboxManager.CheckConfig:output_type -> libbox.v1.CheckConfigResponse
	8,  // 16: libbox.v1.LibboxManager.Start:output_type -> libbox.v1.OperationResponse
	8,  // 17: libbox.v1.LibboxManager.Reload:output_type -> libbox.v1.OperationResponse
	8,  // 18: libbox.v1.LibboxManager.Restart:output_type -> libbox.v1.OperationResponse
	8,  // 19: libbox.v1.LibboxManager.Stop:output_type -> libbox.v1.OperationResponse
	9,  // 20: libbox.v1.LibboxManager.GetState:output_type -> libbox.v1.ServiceState
	9,  // 21: libbox.v1.LibboxManager.SubscribeState:output_type -> libbox.v1.ServiceState
	10, // 22: libbox.v1.LibboxManager.GetSystemProxyStatus:output_type -> libbox.v1.SystemProxyStatus
	10, // 23: libbox.v1.LibboxManager.SetSystemProxy:output_type -> libbox.v1.SystemProxyStatus
	13, // [13:24] is the sub-list for method output_type
	2,  // [2:13] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_libbox_v1_manager_proto_init() }
func file_api_libbox_v1_manager_proto_init() {
	if File_api_libbox_v1_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_libbox_v1_manager_proto_rawDesc), len(file_api_libbox_v1_manager_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_libbox_v1_manager_proto_goTypes,
		DependencyIndexes: file_api_libbox_v1_manager_proto_depIdxs,
		EnumInfos:         file_api_libbox_v1_manager_proto_enumTypes,
		MessageInfos:      file_api_libbox_v1_manager_proto_msgTypes,
	}.Build()
	File_api_libbox_v1_manager_proto = out.File
	file_api_libbox_v1_manager_proto_goTypes = nil
	file_api_libbox_v1_manager_proto_depIdxs = nil
}
